### ISSUE TITLE
Recursive definition

### ISSUE THREAD

**Issue by donpatrice** [monomonedula/nvelope#1]
Is there a way for recursive definitions? So for example let's say we want to consider sections in an article. A section have a title and maybe some subsections. The corresponding json could look like:

```
{
    "title": "This is a really nice title",
    "sections": [
        {
            "title": "Oh this title is even nicer"
            "sections: [
                {
                     "title: "Not so nice title, no subsections"
                }
            ]
        },
        {
             "title": "Section without subsection"
        }
    ]
```
So we could start with:
```
@dataclass
class Section(Obj):
    _conversion = {"title": string_conv}

    title: str
```
But obviously the maybe subsections are missing. Is there a way to model that? Thanks.

**Comment by monomonedula** [comment]
The only way to do it is some monkey-patching.
For python 3.8 it would be:

```python
from __future__ import annotations

from dataclasses import dataclass
from typing import List

from nvelope import Obj, string_conv, ListConversion, CompoundConv


@dataclass
class Section(Obj):
    _conversion = {"title": string_conv}

    title: str
    sections: MaybeMissing[List[Section]]


Section._conversion["sections"] = ListConversion(CompoundConv(Section))

```


You may want to use the latest version 0.3.1 with better support for string  type annotations (namely, `MaybeMissing` logic).

**Comment by donpatrice** [comment]
Thank you so much for the quick reply and the nice work. There is one little question left. If I now have an JSON with an array of sections I would do something like:

```python3
class Sections(Arr):
    conversion = Compound(Section)

sections = Sections.from_json(json_file)
```
right?
And then I can do:
```python3
foo = Section.from_json(
    {
        "title": "bar",
        "sections": Sections.from_json(json_file).as_json()
    }    
)
```
Is that the way how I do it properly? Or can I somehow "directly" assign the list of sections to `foo`?

Thanks a lot!

**Comment by monomonedula** [comment]
@donpatrice if I get you right, you might wanna do something like this:

```python
foo = Section.from_json({"title": "bar"})
foo.sections = Jst(list(sections))    # use Jst wrapper since we defined sections as MaybeMissing attribute
```
`Sections` you defined here is neither an equivalent of `List[Sections]` nor is it an equivalent of `MaybeMissing[List[Sections]]`, so your second block of code is not the way to go.


However, it seems to me that you don't need to define the `Sections` class to do what you are describing here. It can be done must simpler this way:
```python
foo = Section.from_json(
     {
          "title": "bar",
          "sections": json_file 
     }
)
```
or 

```python
foo = Section(
    title="bar",
    sections=[Section.from_json(record) for record in json_file]
)

```


Note: in the first code block you used wrong class. It must be `CompoundConv` instead of `Compound`

**Comment by donpatrice** [comment]
Thanks a lot @monomonedula, both for your help and the great work!
> Note: in the first code block you used wrong class. It must be CompoundConv instead of Compound

Yes you are right, that was a typo.
